name: type-hint-check

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Print working directory
        run: pwd

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run type checker
        run: make typing
